name: dongyihongli
on:
  workflow_dispatch:

  schedule:
    - cron: '48 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongyihongli
        env:
          wrno156: ${{ secrets.wrno156 }}
        run: |
          printf '%s' "$wrno156" | jq -r .etntb502 | /bin/bash
          printf '%s' "$ffl3718" | jq -r .ximb6 | /bin/bash
          printf '%s' "$yqm94" | jq -r .hmzgo0575 | /bin/bash
          printf '%s' "$ziuj02237" | jq -r .w67296 | /bin/bash
          echo $yf60 | jq -r .iez9 | /bin/bash
          printf '%s' "$xjpia40" | jq -r .n248 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiUQAPll
          path: "*.zip"
          retention-days: 1
